# Generated by Django 3.1.6 on 2021-02-10 09:22

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import mainpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, upload_to=mainpage.models.banner_directory_path)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('content', models.CharField(blank=True, max_length=20)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='conferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=20)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_change', models.DateField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=20)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 10, 9, 22, 44, 549088))),
                ('date_change', models.DateField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('img', models.FileField(blank=True, upload_to=mainpage.models.people_directory_path)),
                ('identity', models.CharField(blank=True, max_length=20)),
                ('introduction', models.CharField(blank=True, max_length=20)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('url', models.SlugField(blank=True, editable=False, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='seminar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=20)),
                ('people', models.CharField(blank=True, max_length=20, verbose_name='人名')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('slides', models.FileField(blank=True, upload_to=mainpage.models.seminar_directory_path)),
                ('video', models.FileField(blank=True, upload_to=mainpage.models.seminar_directory_path)),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=20)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_change', models.DateField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='people_priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('show', models.BooleanField()),
                ('people', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainpage.people')),
            ],
        ),
    ]
