# Generated by Django 3.1.7 on 2021-03-12 11:22

import datetime
from django.db import migrations, models
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210214_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='papers_categroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroy_name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='papers',
            name='date_change',
        ),
        migrations.AddField(
            model_name='papers',
            name='paper_file',
            field=models.FileField(blank=True, upload_to=mainpage.models.paper_directory_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 11, 22, 24, 125010)),
        ),
        migrations.AddField(
            model_name='papers',
            name='papers_categroy',
            field=models.ManyToManyField(to='mainpage.papers_categroy'),
        ),
    ]
