# Generated by Django 3.1.7 on 2021-03-12 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210312_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 11, 29, 31, 724603)),
        ),
    ]
