# Generated by Django 3.1.7 on 2021-03-12 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20210312_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='date_add',
        ),
        migrations.AddField(
            model_name='papers',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 12, 26, 13, 573875)),
        ),
    ]
