# Generated by Django 3.1.7 on 2021-03-12 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20210312_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 12, 28, 33, 115133)),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 12, 28, 33, 116213)),
        ),
    ]
