# Generated by Django 3.1.7 on 2021-03-12 13:42

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20210312_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='content',
            new_name='awards',
        ),
        migrations.AddField(
            model_name='people',
            name='classes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='people',
            name='cv',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='people',
            name='home',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='people',
            name='links',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='people',
            name='pre',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='people',
            name='pub',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 13, 42, 12, 739136)),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 13, 42, 12, 740266)),
        ),
    ]
