# Generated by Django 3.1.7 on 2021-03-21 13:15

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20210312_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, max_length=20)),
                ('people', models.CharField(blank=True, max_length=20, verbose_name='人名')),
                ('location', models.CharField(blank=True, max_length=20)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('slides', models.FileField(blank=True, upload_to=mainpage.models.class_directory_path)),
                ('video', models.FileField(blank=True, upload_to=mainpage.models.class_directory_path)),
                ('date_add', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 13, 15, 43, 893927)),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 13, 15, 43, 895107)),
        ),
    ]
