# Generated by Django 3.1.7 on 2021-03-21 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20210321_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 13, 33, 30, 398185)),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 13, 33, 30, 399257)),
        ),
    ]
