# Generated by Django 3.1.7 on 2021-03-21 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_auto_20210321_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='category',
            field=models.CharField(choices=[('Applied Mathematics', 'Applied Mathematics'), ('Fundamental Mathematics', 'Fundamental Mathematics')], max_length=40),
        ),
        migrations.AlterField(
            model_name='classes',
            name='location',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='classes',
            name='topic',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 13, 38, 10, 673483)),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 13, 38, 10, 674547)),
        ),
    ]
