# Generated by Django 3.1.7 on 2021-03-23 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20210321_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 2, 18, 39, 236234)),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 2, 18, 39, 239068)),
        ),
    ]
