# Generated by Django 3.1.7 on 2021-03-23 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20210323_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 2, 45, 21, 369484)),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 2, 45, 21, 371666)),
        ),
    ]
