# Generated by Django 3.1.7 on 2021-03-23 02:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20210323_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classes',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 2, 56, 38, 642946)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 2, 56, 38, 645008)),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
