# Generated by Django 3.1.7 on 2021-03-23 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_auto_20210323_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='classes',
            name='people',
            field=models.CharField(blank=True, max_length=40, verbose_name='人名'),
        ),
        migrations.AlterField(
            model_name='conferences',
            name='topic',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 3, 23, 24, 609436)),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 3, 23, 24, 611672)),
        ),
        migrations.AlterField(
            model_name='papers',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='papers_categroy',
            name='categroy_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='people',
            name='identity',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='people',
            name='introduction',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='people',
            field=models.CharField(blank=True, max_length=40, verbose_name='人名'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='topic',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='themes',
            name='topic',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
